import "./globals.css"

import { Montserrat } from "next/font/google"
const montserrat = Montserrat({ subsets: ["latin"] })

import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"
import { GoTop } from "@/components/GoTop"

export const metadata = {
	title: {
		default: "Colegiado de Computação",
		template: "%s | COLCIC",
	},
	description: "Generated by create next app",
	keywords: "colegiado, computação, uesc, ciência, colcic",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pt-br" className={montserrat.className}>
			<body>
				<Header />
				<GoTop />
				{children}
				<Footer />
			</body>
		</html>
	)
}
