import "./globals.css"

import { Montserrat } from "next/font/google"
import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"
const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata = {
	title: "Colegiado de Ciência da Computação",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pt-br" className={montserrat.className}>
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
